# Generated by Django 5.1.6 on 2026-01-20 15:36

from django.db import migrations
from django.conf import settings

def create_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')

    if not User.objects.filter(email="admin@example.com").exists():
        user = User(
            email="admin@example.com",
            is_staff=True,
            is_superuser=True,
        )
        user.set_password("admin123")  # ✅ hash password
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
