# Generated by Django 5.1.6 on 2026-01-20 15:36

from django.db import migrations


def create_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')  # your custom user model

    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='admin123'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
