# Generated by Django 5.1.6 on 2025-12-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('complete', 'Complete'), ('bulk', 'Bulk')], default='pending', max_length=10),
        ),
    ]
