from django.urls import path
from .views import (
    create_supplier,
    create_buyer,
    create_season,
    create_drop,
    create_product,
    create_order,
    create_delivery,
    SupplierListView,
    BuyerListView,
    SeasonListView,
    DropListView,
    ProductListView,
    OrderListView,
    DeliveryListView,
    edit_supplier,
    delete_supplier,
    update_order_status,
    edit_buyer,
    delete_buyer,
    edit_season,
    delete_season,
    edit_drop,
    delete_drop,
    edit_product,
    delete_product,
)

urlpatterns = [
    path('create-supplier/', create_supplier, name='create-supplier'),
    path('create-buyer/', create_buyer, name='create-buyer'),
    path('create-season/', create_season, name='create-season'),
    path('create-drop/', create_drop, name='create-drop'),
    path('create-product/', create_product, name='create-product'),
    path('create-order/', create_order, name='create-order'),
    path('create-delivery/', create_delivery, name='create-delivery'),

    path('supplier-list/', SupplierListView.as_view(), name='supplier-list'),
    path('buyer-list/', BuyerListView.as_view(), name='buyer-list'),
    path('season-list/', SeasonListView.as_view(), name='season-list'),
    path('drop-list/', DropListView.as_view(), name='drop-list'),
    path('product-list/', ProductListView.as_view(), name='product-list'),
    path('order-list/', OrderListView.as_view(), name='order-list'),
    path('update-order-status/<int:pk>/', update_order_status, name='update-order-status'),
    path('delivery-list/', DeliveryListView.as_view(), name='delivery-list'),

    path('edit-supplier/<int:pk>/', edit_supplier, name='edit-supplier'),
    path('delete-supplier/<int:pk>/', delete_supplier, name='delete-supplier'),
    path('edit-buyer/<int:pk>/', edit_buyer, name='edit-buyer'),
    path('delete-buyer/<int:pk>/', delete_buyer, name='delete-buyer'),
    path('edit-season/<int:pk>/', edit_season, name='edit-season'),
    path('delete-season/<int:pk>/', delete_season, name='delete-season'),
    path('edit-drop/<int:pk>/', edit_drop, name='edit-drop'),
    path('delete-drop/<int:pk>/', delete_drop, name='delete-drop'),
    path('edit-product/<int:pk>/', edit_product, name='edit-product'),
    path('delete-product/<int:pk>/', delete_product, name='delete-product'),
]
